backend:
  name: test-repo

media_folder: assets/uploads

collections:
  - label: "Posts"
    label_singular: "Post"
    name: "posts"
    folder: "_posts"
    create: true
    fields:
      - label: Title
        name: title
        widget: string

      - label: Title (i18nized)
        name: i18n_title
        widget: ncw-i18nize
        langs: ["en", "kr", "de"]
        wrap_widget: object
        wrap_fields:
          - label: Name
            name: name
            widget: string
          - label: Age
            name: age
            widget: number
            required: false

      - label: ID
        name: id
        widget: ncw-id
        prefix: post
        timestamp: true
        hint: This widget generate an unique read-only id

      # - label: Categories
      #   name: cats
      #   widget: ncw-file-relation
      #   collection: setting
      #   file: cats
      #   target_field: cats
      #   id_field: id
      #   display_fields: name
      #   multiple: true

  - label: Pages
    name: pages
    files:
      - label: Home
        name: home
        file: _data/_home.json
        fields:
          - label: Title
            name: title
            widget: string

          - label: Featured Posts
            name: featured
            widget: ncw-reorder
            collection: posts
            id_field: id
            display_fields: ["title", "id"]
            hint: "this reorder widget display entries from `posts` collection."

          - label: Featured Posts (Custom)
            name: featuredCustom
            widget: custom-reorder
            collection: posts
            id_field: id
            display_fields: ["title", "id"]
            hint: "this is a reorder widget with custom control"

  - label: Setting
    name: setting
    files:
      - label: Categories
        name: cats
        file: _data/_cats.json
        fields:
          - label: Categories
            name: cats
            widget: list
            allow_add: true
            fields:
              - label: Name
                name: name
                widget: string

              - label: Description
                name: desc
                widget: text

              - label: ID
                name: id
                widget: ncw-id
                prefix: cats
